services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - server-infra

  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - server-infra

volumes:
  uptime-kuma-data:

networks:
  server-infra:
    name: server-infra
    external: true
